apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-frontend
  template:
    metadata:
      labels:
        app: flight-frontend
    spec:
      containers:
      - name: frontend
        image: 603433801149.dkr.ecr.ap-south-1.amazonaws.com/flight-frontend:latest
        ports:
        - containerPort: 5000
